#!/bin/bash

echo "TEST BoundedBuf program"

SPECIAL="-maxTid=$[AVAIL_PROCS + 40]"

rrrun ${SPECIAL} -classpath=boundedbuf.jar -quiet -maxWarn=1 -noTidGC -tool=HB examples.boundedbuffer.BoundedBuffer
