#!/bin/bash

echo "TEST AirlineTicket program"

SPECIAL="-maxTid=$[AVAIL_PROCS + 40]"

rrrun ${SPECIAL} -classpath=airlineticket.jar -quiet -maxWarn=1 -noTidGC -tool=HB examples.airlinetickets.Airlinetickets
